# Generated by Django 5.1.15 on 2026-07-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
