# Generated by Django 5.1.15 on 2026-09-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_staff_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
