# Generated by Django 5.1.15 on 2026-09-26 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_staff_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
    ]
