# Generated by Django 5.1.15 on 2026-07-25 06:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "quantity_on_hand",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "unit_of_measure",
                    models.CharField(
                        choices=[
                            ("g", "Grams"),
                            ("kg", "Kilograms"),
                            ("l", "Liters"),
                            ("ml", "Milliliters"),
                            ("pcs", "Pieces"),
                        ],
                        default="g",
                        max_length=3,
                    ),
                ),
                (
                    "reorder_threshold",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cost_per_unit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity_delta",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("restock", "Restock"),
                            ("order_deduction", "Order Deduction"),
                            ("waste", "Waste"),
                            ("correction", "Correction"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_movements",
                        to="inventory.ingredient",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
