# Generated by Django 5.1.15 on 2026-07-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="is_low_stock_alerted",
            field=models.BooleanField(default=False),
        ),
    ]
