# Generated by Django 5.1.15 on 2026-07-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_ingredient_is_low_stock_alerted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="quantity_on_hand",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
