# Generated by Django 5.1.15 on 2026-09-03 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_ingredient_quantity_on_hand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="reason",
            field=models.CharField(
                choices=[
                    ("restock", "Restock"),
                    ("order_deduction", "Order Deduction"),
                    ("order_reversal", "Order Reversal"),
                    ("waste", "Waste"),
                    ("correction", "Correction"),
                ],
                max_length=20,
            ),
        ),
    ]
