# Generated by Django 5.1.15 on 2026-08-06 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_ingredient_quantity_on_hand"),
        ("menu", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="is_available",
            new_name="is_active",
        ),
        migrations.AlterField(
            model_name="menuitemingredient",
            name="menu_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredients",
                to="menu.menuitem",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="menuitemingredient",
            unique_together={("menu_item", "ingredient")},
        ),
    ]
