# Generated by Django 5.1.15 on 2026-09-27 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_rename_is_available_menuitem_is_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="menu_item_avatars/"
            ),
        ),
    ]
